# Generated by Django 5.0.2 on 2024-02-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='icecreams',
            fields=[
                ('ItemNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('IcecreamName', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
