# Generated by Django 5.0.2 on 2024-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableItems',
            fields=[
                ('ItemNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
