# Generated by Django 5.0.2 on 2024-02-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_availableitems_itemname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableItems',
        ),
    ]
